### ISSUE TITLE
Compiles, but not exporting

### ISSUE THREAD

**Issue by richrumble** [libyal/libpff#25] opened 2016-07-31 00:00 UTC
I've managed to compile in MinGW using libpff-experimental-20131028.tar.gz
My build command was:
CPPFLAGS=-DWINVER=0x0501 ./configure --prefix=/mingw --enable-verbose-output --enable-static-executables
## make -j4

When exporting, all I get is a lot of folder structure, no files output. I'm using the Enron Dataset as a test. 

pffexport.exe -f rtf -m all c:\Users\xxx\Downloads\EnronDataOrg_AED_Mailbox-PSTs_20090122\allen-p.pst

I'm happy to attach or supply anything you want. I had one hiccup compiling in C++ 2010 I couldn't get past but that is a different issue "The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _close"

**Comment by joachimmetz** [comment] 2016-08-18 16:24
Missed this one earlier. Need to check if I can reproduce this, when time permits.

**Comment by joachimmetz** [comment] 2016-11-18 21:41
Looks like this was an issue in the experimental version. Please try with the last alpha version https://github.com/libyal/legacy/tree/master/libpff or with the bleeding edge experimental version in this git repository. Closing this issue, seeing it will be addressed when https://github.com/libyal/libpff/issues/3 is completed.

**Closed by joachimmetz** 2016-11-18 21:41 UTC
Labels: question
