### ISSUE TITLE
libpff_data_array_read_entries: invalid number of array entries value out of bounds when reading from a compressed OST

### ISSUE THREAD

**Issue by nelley** [libyal/libpff#70] opened 2018-10-07 11:02 UTC
```
for message in folder.sub_messages:
IOError: pypff_folder_get_sub_messages: unable to retrieve number of sub messages. libpff_data_array_read_entries: invalid number of array entries value out of bounds. libpff_data_array_read: unable to read data array entries. libpff_io_handle_read_descriptor_data_list: unable to read data array. libpff_table_read: unable to read descriptor: 2292334 data: 85339494 list. libpff_item_values_read: unable to read table. libpff_folder_determine_sub_messages: unable to read descriptor identifier: 2292334. libpff_folder_get_number_of_sub_messages: unable to determine sub messages.
-------------------------------------------
```
I got a error when I iterating the sub messages. I noticed only the folder contains the big number of messages will trigger this error.
p.s. over 20,000 messages in one folder

**Comment by praveenmaniyan** [comment] 2020-02-21 09:52
I am getting the above error message for my OST file which has more than 40,000 messages. May I know why this issue was closed, or is there a work around for the same? Is this a limitation of some array size in the Code?

**Comment by joachimmetz** [comment] 2020-02-21 10:49
@praveenmaniyan the original reporter close the issue, so I have no idea. 

Can you provide the full error you are encountering?

**Comment by praveenmaniyan** [comment] 2020-02-21 12:38
`OSError: pypff_folder_get_number_of_sub_messages: unable to retrieve number of sub messages. libpff_data_array_read_entries: invalid number of array entries value out of bounds. libpff_data_array_read: unable to read data array entries. libpff_io_handle_read_descriptor_data_list: unable to read data array. libpff_table_read: unable to read descriptor: 8590 data: 39871842 list. libpff_item_values_read: unable to read table. libpff_folder_determine_sub_messages: unable to read descriptor identifier: 8590. libpff_folder_get_number_of_sub_messages: unable to determine sub messages.`

The above the error encountered. I have more than 40,000 messages in one of my OST/PST folder, and this error is encountered at that particular folder.

Please let me know a fix so that I use this library.

**Comment by joachimmetz** [comment] 2020-02-21 12:56
Which version of libpff/pypff are you using. Note that work on pypff is not yet completed https://github.com/libyal/libpff/issues/2.

**Comment by praveenmaniyan** [comment] 2020-02-21 13:26
I am using the latest release "libpff-experimental-20180714" version.

**Comment by praveenmaniyan** [comment] 2020-02-22 04:57
@joachimmetz , one update on this issue. I exported the OST to a PST, and the folder had 38714 messages. This got successfully exported when the input file was PST. However, the same script failed for OST input file. So, this error seems to be happening only for OST files.

**Comment by joachimmetz** [comment] 2020-02-23 08:33
@praveenmaniyan 

* could you provide some information about the OST data format version / type
* any additional context on the message/folder type that is generating the error?

**Comment by praveenmaniyan** [comment] 2020-02-25 04:32
I ran the pffinfo command on the OST, please find below the output.
`pffinfo 20120802

Personal Folder File information:
        File size:              9440403456 bytes
        File content type:      Offline Storage Tables (OST)
        File type:              64-bit
        Encryption type:        none

Message store:`

The message/folder type is "Inbox", please find below the complete error of the script run. For some folders like "Deleted Items" and some other Personal folders it is running fine. Please let me know for any further information, also any specific command you want me to run on the OST file.

`Folder Name ----> IPM_SUBTREE
Number of messages is ---> 0
 Folder Name ----> Organization Forms
Number of messages is ---> 0
 Folder Name ----> EFORMS REGISTRY
 Number of messages is ---> 0
 Folder Name ----> NON_IPM_SUBTREE
 Number of messages is ---> 0
 Folder Name ----> Root - Public
 Number of messages is ---> 0
 Folder Name ----> Common Views
 Number of messages is ---> 0
 Folder Name ----> Reminders
 Number of messages is ---> 0
 Folder Name ----> To-Do Search
 Number of messages is ---> 0
 Folder Name ----> Missed Conversations
 Number of messages is ---> 0
 Folder Name ----> Voice Mail
 Number of messages is ---> 0
 Folder Name ----> Inbox
Traceback (most recent call last):
File "pst_traverse_reporter.py", line 412, in <module>
main(args.PST_FILE, args.title)
File "pst_traverse_reporter.py", line 37, in main
folderTraverse(root)
File "pst_traverse_reporter.py", line 74, in folderTraverse
folderTraverse(folder) # Call new folder to traverse:
File "pst_traverse_reporter.py", line 74, in folderTraverse
folderTraverse(folder) # Call new folder to traverse:
File "pst_traverse_reporter.py", line 76, in folderTraverse
checkForMessages(folder)
File "pst_traverse_reporter.py", line 90, in checkForMessages
print("Number of messages is --->", folder.number_of_sub_messages)
OSError: pypff_folder_get_number_of_sub_messages: unable to retrieve number of sub messages. libpff_data_array_read_entries: invalid number of array entries value out of bounds. libpff_data_array_read: unable to read data array entries. libpff_io_handle_read_descriptor_data_list: unable to read data array. libpff_table_read: unable to read descriptor: 8590 data: 49142534 list. libpff_item_values_read: unable to read table. libpff_folder_determine_sub_messages: unable to read descriptor identifier: 8590. libpff_folder_get_number_of_sub_messages: unable to determine sub messages.`

**Comment by joachimmetz** [comment] 2020-02-25 05:43
@praveenmaniyan based on your output it looks like you are using libpff 20120802 but you indicated earlier that you were using 20180714? Do you have multiple versions on your system?

**Comment by praveenmaniyan** [comment] 2020-02-25 05:50
@joachimmetz , I installed pffinfo only after you requested for OST file information, i.e., on 24-Feb-2020 only. I have used pffinfo executable which I installed using apt install. However, for running the code and extracting messages from OST I have been using the library/code of 20180714.

Can you please re-direct me to the code/module of C/C++ where is array is initialized, and how the size calculation is done, so that I can try to debug it from my side.

**Comment by joachimmetz** [comment] 2020-02-25 05:59
thx for the clarification

The error contains the location:
```
OSError: pypff_folder_get_number_of_sub_messages: unable to retrieve number of sub messages.
libpff_data_array_read_entries: invalid number of array entries value out of bounds.
libpff_data_array_read: unable to read data array entries.
libpff_io_handle_read_descriptor_data_list: unable to read data array.
libpff_table_read: unable to read descriptor: 8590 data: 49142534 list.
libpff_item_values_read: unable to read table. libpff_folder_determine_sub_messages: unable to read descriptor identifier: 8590.
libpff_folder_get_number_of_sub_messages: unable to determine sub messages.
```

https://github.com/libyal/libpff/blob/34c48fb28e0d28f829d801d7bce646ef8eebe6d4/libpff/libpff_data_array.c#L520

It might help to get some format debug output also see https://github.com/libyal/libpff/wiki/Troubleshooting#verbose-and-debug-output

**Comment by LastTechBender** [comment] 2020-05-14 13:14
Hi @joachimmetz @praveenmaniyan 

I am getting a similar error when trying to read a large OST file. Has there been any updates or solutions to this issue?

Best wishes

**Comment by ftang001** [comment] 2021-09-19 21:20
Hi @joachimmetz I had similar errors with a large (16 Gb) OST file, using both the 2018 version and the current source.  With the help of your docs (many thanks!) I eventually wrote my own crude reader and successfully extracted the full file, with no corruption.  I wasn't able to confirm it, but I suspect the problem with libpff may be related to compressed internal node blocks (indexes), which appear in large folders and messages; my less-than-elegant approach to the compression issue was to run a first pass over the file and inflate all compressed blocks into a new file before walking the folder structure.

**Comment by joachimmetz** [comment] 2021-09-20 03:25
@ftang001 can you share the test data? Otherwise this issue will unlike to be addressed soon

**Comment by shmulikipod1151** [comment] 2021-11-01 14:41
@joachimmetz Hi,
Sorry for not responding, I was on vacation for a few days.
My ost is pretty big, is it possible to share the script that can produce one?
Basically, it's a python script that sends the same mail many times (about 4000 times makes it happen), and the outbox becomes a folder with many items and reproduces the issue.
If that's not convinient, I will create a fresh .ost for this purpose.

**Comment by joachimmetz** [comment] 2021-11-01 18:08
@shmulikipod1151 excellent yes that is already a step in the right direction, I'm doing similar things with toher formats on https://github.com/dfirlabs. Happy to create a repo if you're fine sharing your script under a FOSS license. 

The annoying thing with PST/OST is that one needs Microsoft Outlook, I would need to dig that up, and that might take a while, since it is not one of the data formats currently on the top of my list.

**Comment by shmulikipod1151** [comment] 2021-11-02 14:18
https://github.com/dfirlabs this is awesome work, thanks! 
Let me try and save you some time by generating a minimal OST that reproduces the issue. 
If that won't work (the OST will be huge) I will share the script.

**Comment by shmulikipod1151** [comment] 2021-11-09 13:59
@joachimmetz , I've managed to create an ost that reproduces the issue
I just sent my self the same email 15000 times
(I wrote a powershell script for it)
I got this 1gb file, how can I share it with you? Can I send you a link by mail?

**Comment by joachimmetz** [comment] 2021-11-09 14:30
Excellent, much appreciated for the 1G file, upload to Google Drive or equiv and mail me the link, that should work.

If you want to share the powershell script I can create https://github.com/dfirlabs/pst-specimens (or equiv) and you send a PR to that project. So that the script is linked to you as contributor as well.

**Comment by joachimmetz** [comment] 2021-11-14 16:20
Looks like compressed size of descriptor is passed instead of uncompressed size of data block.

**Comment by joachimmetz** [comment] 2021-11-14 16:26
With thanks to @shmulikipod1151 I was able to reproduce the issue, which is limited to compressed OST files.

Note that this could have been solved in 2018 if people would provide test data or debug output  https://github.com/libyal/libpff/wiki/Troubleshooting#verbose-and-debug-output.

**Comment by joachimmetz** [comment] 2021-11-14 16:54
Changes in https://github.com/libyal/libpff/commit/9d6a3f08379abe05c332a83f299cb5fab07348cc

**Closed by joachimmetz** 2021-11-14 16:54 UTC
Labels: enhancement

**Comment by smclinden** [comment] 2024-05-08 21:36
I am seeing this issue as well.

```
pffinfo 20240427

Personal Folder File information:
	File size:		600867840 bytes
	File content type:	Personal Storage Tables (PST)
	File type:		64-bit
	Encryption type:	compressible

Message store:
	Folders:		Subtree, Inbox, Outbox, Wastbox, Sentmail, Views, Common views, Finder
	Password checksum:	N/A
```

and

```
pffexport 20240427

Opening file.
Recovering items.
Unable to export file.
libpff_index_value_read_data: invalid file offset value out of bounds.
libpff_recover_index_values: unable to read offsets index value.
libpff_recover_data_blocks: unable to recover index node at offset: 599707136.

libpff_recover_items: unable to recover data blocks.
libpff_file_recover_items: unable to recover items.
export_handle_export_file: unable to recover items.
```

I get similar issues with the OST.
