### ISSUE TITLE
Tool chain does not work, properly, on OS X Sierra (10.12.5)

### ISSUE THREAD

**Issue by smclinden** [libyal/libpff#41] opened 2017-07-13 11:42 UTC
As an example, to correct errors such as the following, I have had to manually build all the dependencies rather than use the "synclibs.sh" script.

libtool: link: (cd ".libs" && rm -f "libpff.dylib" && ln -s "libpff.1.dylib" "libpff.dylib")
../libtool: line 5679: cd: /Users/seanmclinden/Cyfir/Murray/Exchange: No such file or directory
libtool: link: (cd .libs/libpff.lax/libcsplit.a && ar x "/Users/seanmclinden/Cyfir/Murray/Exchange Logs/libpff/libpff/../libcsplit/.libs/libcsplit.a")
../libtool: line 1720: cd: .libs/libpff.lax/libcsplit.a: No such file or directory

**Comment by joachimmetz** [comment] 2017-07-13 12:17
Thx for the feedback. I'll try to reproduce this to determine what has changed on macOS.

**Comment by smclinden** [comment] 2017-07-19 16:09
I did see this warning:

checking for egrep... /usr/bin/grep -E
checking whether gcc needs -traditional... no
checking whether make sets $(MAKE)... (cached) yes
configure: WARNING: Libtool does not cope well with whitespace in `pwd`

**Comment by deeg** [comment] 2018-03-27 17:03
I am also not able to install this on Mac OSX 10.13.3

I did not see the warning mentioned by @smclinden.

**Comment by deeg** [comment] 2018-03-27 19:10
Yes I also cannot install the tool on OS X High Sierra (10.13.3)

![screen shot 2018-03-27 at 12 09 16 pm](https://user-images.githubusercontent.com/2857769/37989226-b2242dba-31b7-11e8-904b-f7ef8fb19f25.png)

Clicking install anyways errors out. Any pointers in making it work on my version of OS X?

I did not see the warning @smclinden mentioned.

**Comment by joachimmetz** [comment] 2018-03-27 19:12
@deeg libpff does not come with an install, what did you try to install?

**Comment by deeg** [comment] 2018-03-27 20:33
@joachimmetz, thanks for quick response.

I followed the instructions [on this page](https://github.com/libyal/libpff/wiki/Building#using-mac-os-x-pkgbuild), in order to build a .pkg install file. I then tried running that install file.

FWIW, it was the same steps I tried previously on an older version of Mac OS X (Yosemite) which worked successfully the first time.

**Comment by joachimmetz** [comment] 2018-03-28 03:45
this is likely a different issue then initially reported in this issue.

* make sure your version of xcode and CLI tools is up to date
* try changing the prefix to `/usr/local` due to "System Integrity Protection"

**Comment by deeg** [comment] 2018-03-28 15:34
@joachimmetz, sorry for hijacking another thread, didn't realize it was discussing different topics.

> try changing the prefix to /usr/local due to "System Integrity Protection"

This did the trick, thanks very much!

**Comment by joachimmetz** [comment] 2018-07-14 09:05
Ran default build from a path with a space on High Sierra. 
`/Users/username/Projects/with space/libpff`

```
../libtool: line 5679: cd: /Users/username/Projects/with: No such file or directory
../libtool: line 1720: cd: .libs/libpff.lax/libcerror.a: No such file or directory
```

This looks like an issue in `../libtool` which is generated by glibtoolize on MacOS. 

```
glibtoolize --version
glibtoolize (GNU libtool) 2.4.6
```

For now the recommendation is not to build from a path with spaces.

**Comment by joachimmetz** [comment] 2018-07-14 11:22
Closing issue

**Closed by joachimmetz** 2018-07-14 11:22 UTC
Labels: question
